const apiRouter = require('./newsRouter');
const authRouter = require('./authRouter');
const adminRouter = require('./adminRouter');
const newDetailRouter = require('./newDetailRouter');
const tournamentsRouter = require('./tournamentsRouter');
const commentsRouter = require('./commentsRouter');
const clubsRouter = require('./clubsRouter');
const resultsRouter = require('./resultsRouter');
const videosRouter = require('./videosRouter');
const route = (app) => {
  app.use('/api/v1/news', apiRouter);
  app.use('/api/v1/new-detail', newDetailRouter);
  app.use('/api/v1/auth', authRouter);
  app.use('/api/v1/admin', adminRouter);
  app.use('/api/v1/tournaments', tournamentsRouter);
  app.use('/api/v1/comments', commentsRouter);
  app.use('/api/v1/clubs', clubsRouter);
  app.use('/api/v1/results', resultsRouter);
  app.use('/api/v1/videos', videosRouter);
};
module.exports = route;
